version: '3.5'

services:
  ms-car-info:
    container_name: ms-car-info
    build: ./CarInfo.API
    hostname: microservicecarinfo
    restart: always
    networks:
      - backend
    ports:
      - "49157:49157"

networks:
  backend:
    name: backend
    external: false  